### ISSUE TITLE
Rescue on Email Errors

### ISSUE THREAD

**Issue by drernie** [TheSwanFactory/igwet#60]
https://my.papertrailapp.com/groups/21147432/events?focus=1248314668309753880

`to: [{"dlmadd", "dlmadd@sbcglin"}]} 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |  
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | 12:53:47.600 request_id=312991d9891b4035c25ddae69dda2131 [info] Sent 500 in 5840ms 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | 12:53:47.600 request_id=312991d9891b4035c25ddae69dda2131 [debug] Converted error Bamboo.ApiError to 500 response 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | 12:53:47.602 [error] #PID<0.18219.0> running IgwetWeb.Endpoint (connection #PID<0.18186.0>, stream id 11) terminated 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | Server: www.igwet.com:80 (http) 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | Request: GET /rsvp/send_email/us.kingsway%2B2020-10-04 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | ** (exit) an exception was raised: 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |     ** (Bamboo.ApiError) There was a problem sending the email through the Mailgun API. 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |  
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | Here is the response: 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |  
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | "{\n  \"message\": \"'to' parameter is not a valid address. please check documentation\"\n}" 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |  
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | Here are the params we sent: 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |  
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | "from=Kingsway+Community+Church+%3Coffice%40kingsway.us%3E&h%3AList-Archive=%3Chttps%3A%2F%2Fwww.igwet.com%2Fgroups%2Fa4f5828e-1859-4f1b-8341-7a88e1559c11&h%3Asender=postmaster%40mg.igwet.com&html=Dear+dlmadd%2C%0A%3Cdiv+style%3D%27white-space%3A+pre-line%3B%27%3EWe+look+forward+to+seeing+you%21%0AClick+%3Ca+href%3D%27https%3A%2F%2Fwww.igwet.com%2Frsvp%2Ffor%2Fus.kingsway%252B2020-10-04%2Fdlmadd%2540sbcglin%27%3Ehere%3C%2Fa%3E+to+tell+us+how+many+will+attend+this+week+%28enter+0+if+not+coming%29.%0A+Note%3A+if+you+use+this+personalized+link%2C+you+don%27t+need+to+use+the+public+link+sent+to+everyone.%0A%3Chr%3EWe+are+all+very+excited+to+able+to+meet+in+person+again%21+To+ensure+everyone%27s+health+and+safety%2C+as+well+as+comply+with+county+guidelines%2C+please+be+sure+to%3A%0D%0A%0D%0A%2A+Register+how+many+are+coming+each+week+%28or+enter+0+so+we+know+you+aren%27t+coming%29%0D%0A%2A+Plan+to+arrive+ten+minutes+early+%28and+bring+a+chair+if+you+can%29%0D%0A%2A+Park+on+the+right+after+you+enter%3A+242+Hillsdale+Ave+San+Jose+CA+95136%0D%0A%2A+Wear+a+face+covering+as+you+go+back+and+forth+to+your+car%0D%0A%2A+Keep+any+children+with+you+%28as+we+do+not+have+childcare%29%0D%0A%2A+Do+NOT+come+if+you+are+feeling+ill+or+have+been+near+anyone+who+tested+positive+for+COVID-19%0D%0A%2A+Join+us+on+Zoom+if+you+aren%27t+coming+in+person+%3Chttps%3A%2F%2Fvcs.zoom.us%2Fj%2F95544175968%3E%3C%2Fdiv%3E&subject=10-04%3A+Kingsway+Sunday+Service&text=Dear+dlmadd%2C%0A%0A%0AWe+look+forward+to+seeing+you%21%0AClick+here+to+tell+us+how+many+will+attend+this+week+%28enter+0+if+not+coming%29.%0A+Note%3A+if+you+use+this+personalized+link%2C+you+don%27t+need+to+use+the+public+link+sent+to+everyone%3A%0A+https%3A%2F%2Fwww.igwet.com%2Frsvp%2Ffor%2Fus.kingsway%252B2020-10-04%2Fdlmadd%2540sbcglin%0A%0AWe+are+all+very+excited+to+able+to+meet+in+person+again%21+To+ensure+everyone%27s+health+and+safety%2C+as+well+as+comply+with+county+guidelines%2C+please+be+sure+to%3A%0D%0A%0D%0A%2A+Register+how+many+are+coming+each+week+%28or+enter+0+so+we+know+you+aren%27t+coming%29%0D%0A%2A+Plan+to+arrive+ten+minutes+early+%28and+bring+a+chair+if+you+can%29%0D%0A%2A+Park+on+the+right+after+you+enter%3A+242+Hillsdale+Ave+San+Jose+CA+95136%0D%0A%2A+Wear+a+face+covering+as+you+go+back+and+forth+to+your+car%0D%0A%2A+Keep+any+children+with+you+%28as+we+do+not+have+childcare%29%0D%0A%2A+Do+NOT+come+if+you+are+feeling+ill+or+have+been+near+anyone+who+tested+positive+for+COVID-19%0D%0A%2A+Join+us+on+Zoom+if+you+aren%27t+coming+in+person+%3Chttps%3A%2F%2Fvcs.zoom.us%2Fj%2F95544175968%3E&to=dlmadd+%3Cdlmadd%40sbcglin%3E" 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |  
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |         (bamboo 1.5.0) lib/bamboo/api_error.ex:63: Bamboo.ApiError.raise_api_error/4 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |         (bamboo 1.5.0) lib/bamboo/mailer.ex:161: Bamboo.Mailer.deliver_now/4 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |         (igwet 0.2.6) lib/igwet_web/controllers/rsvp_controller.ex:119: anonymous fn/5 in IgwetWeb.RsvpController.send_email/2 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |         (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |         (igwet 0.2.6) lib/igwet_web/controllers/rsvp_controller.ex:115: IgwetWeb.RsvpController.send_email/2 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |         (igwet 0.2.6) lib/igwet_web/controllers/rsvp_controller.ex:3: IgwetWeb.RsvpController.action/2 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |         (igwet 0.2.6) lib/igwet_web/controllers/rsvp_controller.ex:3: IgwetWeb.RsvpController.phoenix_controller_pipeline/2 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |         (phoenix 1.5.4) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2 `

**Comment by drernie** [comment]
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | Server: www.igwet.com:80 (http) 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | Request: GET /rsvp/send_email/us.kingsway%2B2020-10-04 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  | ** (exit) an exception was raised: 
Oct 01 05:53:47 d.06884a19-824f-4c51-90c0-c0d3233964c0 igwet/igwet-5c7855b94d-z7q7k web.1  |     ** (Bamboo.ApiError) There was a problem sending the email through the Mailgun API.

**Comment by drernie** [comment]
try do
  opts
  |> Keyword.fetch!(:source_file)
  |> File.read!()
rescue
  e in Bamboo.ApiError -> IO.puts("missing :source_file option")
  e in File.Error -> IO.puts("unable to read source file")
end
